version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/wishlist
      - POSTGRES_USER=wishlist
      - POSTGRES_PASSWORD=wishlist
      - JWT_SECRET=your_jwt_secret_key_here_please_change_in_production
    depends_on:
      - db
    networks:
      - wishlist-network

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wishlist
      - POSTGRES_USER=wishlist
      - POSTGRES_PASSWORD=wishlist
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wishlist-network

volumes:
  postgres-data:

networks:
  wishlist-network:
    driver: bridge
